### ISSUE TITLE
setup_database fails on PostgreSQL

### ISSUE THREAD

**Issue by welshjf** [deginner/desw#22]
See http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.Enum.__init__ (`name` parameter).

Full traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.6.0-py2.7.egg/gunicorn/arbiter.py", line 557, in spawn_worker 
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.6.0-py2.7.egg/gunicorn/workers/base.py", line 126, in init_process 
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.6.0-py2.7.egg/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.6.0-py2.7.egg/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.6.0-py2.7.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.6.0-py2.7.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.6.0-py2.7.egg/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/DeSW-0.0.2-py2.7.egg/desw/__init__.py", line 24, in <module>
    setup_database()
  File "/usr/local/lib/python2.7/dist-packages/DeSW-0.0.2-py2.7.egg/desw/__init__.py", line 19, in setup_database
    SLM_User.metadata.create_all(eng)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/sql/schema.py", line 3745, in create_all
    tables=tables)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/engine/base.py", line 1856, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/engine/base.py", line 1481, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)    
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/sql/ddl.py", line 720, in visit_metadata
    _ddl_runner=self)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/util/langhelpers.py", line 546, in __call__
    return getattr(self.target, self.name)(*arg, **kw)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/sql/sqltypes.py", line 1040, in _on_metadata_create
    t._on_metadata_create(target, bind, **kw)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/dialects/postgresql/base.py", line 1379, in _on_metadata_create
    self.create(bind=bind, checkfirst=checkfirst)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/dialects/postgresql/base.py", line 1317, in create
    bind.execute(CreateEnumType(self))
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/engine/base.py", line 962, in _execute_ddl
    compiled = ddl.compile(dialect=dialect)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/sql/elements.py", line 494, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/sql/ddl.py", line 26, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/sql/compiler.py", line 190, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/sql/compiler.py", line 213, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw) 
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/dialects/postgresql/base.py", line 1616, in visit_create_enum_type
    self.preparer.format_type(type_),
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.14-py2.7.egg/sqlalchemy/dialects/postgresql/base.py", line 1860, in format_type
    raise exc.CompileError("Postgresql ENUM type requires a name.")
CompileError: Postgresql ENUM type requires a name.
```

**Comment by isysd** [comment]
Fixed with sqlalchemy-models v0.0.6.
